### ISSUE TITLE
Unable to receive legitimate Trello Webhook Responses due to failing invalid trello signature.

### ISSUE THREAD

**Issue by NNickey** [18F/trello-webhook-server#11]
I have tried looking multiple times into finding my client Secret key, and instead had no luck and someone online said that I could add in a simple code as it steps in for verification.

However, it still does not work..

![image](https://cloud.githubusercontent.com/assets/3466265/14944472/0a9f3122-0fb1-11e6-8c42-8269832b49a2.png)

**Comment by mgwalker** [comment]
You definitely need your actual client secret.  Trello uses it on their end to sign their webhook requests.  It can be found near the bottom of this page, under the OAuth header:  https://trello.com/app-key

I think your troubles highlight that maybe "client secret" should be renamed to "OAuth client secret," to make it clearer what it needs.

**Comment by mgwalker** [comment]
Not only was the documentation unclear about what the "client secret" refers to, but it also reversed the API token and OAuth client secret descriptions.  I have fixed the documentation in #12.

Let me know if any of this helps you!
